'use client';
import {useEffect,useMemo,useState} from 'react';
import {HSK_LESSON_NUMBER,HSK_VOCABULARY,type HskVocabularyWord} from '../data/hskVocabulary';
type Props={lessonId:string;userId:string|number;onClose:()=>void;review?:boolean};
export default function HskDictionary({lessonId,userId,onClose,review=false}:Props){
 const key=`hsk-dictionary:${userId}`,[progress,setProgress]=useState<Record<string,number>>({}),[position,setPosition]=useState(0),[all,setAll]=useState(!review);
 useEffect(()=>{try{setProgress(JSON.parse(localStorage.getItem(key)||'{}'))}catch{}},[key]);
 const words=useMemo(()=>HSK_VOCABULARY.filter(w=>w.lesson<(HSK_LESSON_NUMBER[lessonId]||1)&&(progress[w.word]||0)<3),[lessonId,progress]),word=words[position%Math.max(1,words.length)];
 const know=(w:HskVocabularyWord)=>{const next={...progress,[w.word]:Math.min(3,(progress[w.word]||0)+1)};setProgress(next);localStorage.setItem(key,JSON.stringify(next));setPosition(p=>words.length>1?p%(words.length-1):0)};
 return <div className="fixed inset-0 z-[80] flex items-center justify-center bg-slate-950/85 p-3 text-slate-900"><div className="flex max-h-[94vh] w-full max-w-3xl flex-col overflow-hidden rounded-2xl bg-white">
 <header className="flex items-center justify-between border-b p-4"><div><h2 className="text-xl font-black">Словарь HSK</h2><p className="text-sm text-slate-500">Выучено {HSK_VOCABULARY.filter(w=>(progress[w.word]||0)>=3).length} из {HSK_VOCABULARY.length}</p></div><button onClick={onClose} className="h-9 w-9 rounded-lg bg-slate-100 text-xl">×</button></header>
 <nav className="flex gap-2 border-b p-2 px-4"><button onClick={()=>setAll(false)} className={`rounded-lg px-3 py-2 font-bold ${!all?'bg-cyan-500 text-white':'bg-slate-100'}`}>Повторение</button><button onClick={()=>setAll(true)} className={`rounded-lg px-3 py-2 font-bold ${all?'bg-cyan-500 text-white':'bg-slate-100'}`}>Все слова</button></nav>
 {all?<div className="overflow-y-auto p-4"><div className="grid gap-2 sm:grid-cols-2">{HSK_VOCABULARY.map(w=><div key={`${w.lesson}-${w.word}`} className="flex items-center gap-3 rounded-xl border p-3"><div className="flex-1"><b className="text-2xl">{w.word}</b><span className="ml-2 font-semibold text-cyan-700">{w.pinyin}</span><div className="text-sm text-slate-600">{w.translation} · урок {w.lesson}</div></div><b className={(progress[w.word]||0)>=3?'text-emerald-600':'text-amber-600'}>{progress[w.word]||0}/3</b></div>)}</div></div>:
 <div className="grid min-h-[350px] place-items-center p-5">{word?<div className="w-full max-w-md text-center"><div className="mb-2 text-sm font-bold text-slate-400">УРОК {word.lesson} · ОСТАЛОСЬ {words.length}</div><div className="rounded-2xl bg-cyan-50 p-8"><div className="text-6xl font-black">{word.word}</div><div className="mt-3 text-xl font-bold text-cyan-700">{word.pinyin}</div><div className="mt-4 text-lg">{word.translation}</div><div className="mt-5 font-bold text-slate-500">Знаю: {progress[word.word]||0} / 3</div></div><div className="mt-4 flex gap-3"><button onClick={()=>setPosition(p=>p+1)} className="flex-1 rounded-xl bg-slate-200 p-3 font-black">Ещё повторить</button><button onClick={()=>know(word)} className="flex-1 rounded-xl bg-emerald-500 p-3 font-black text-white">Знаю</button></div></div>:<div className="text-center"><div className="text-5xl">🎉</div><h3 className="mt-3 text-xl font-black">Слова для повторения закончились</h3><p className="text-slate-500">Они остаются во вкладке «Все слова».</p><button onClick={onClose} className="mt-5 rounded-xl bg-cyan-500 px-6 py-3 font-black text-white">Перейти к уроку</button></div>}</div>}
 </div></div>}