'use client';
import { useMemo, useRef, useState } from 'react';

export interface LetterJumpConfig { title: string; instruction: string; items: string[]; rounds: number; lives: number }
export interface LetterJumpResult { score: number; total: number; mistakes: number; livesLeft: number; status: 'completed' | 'failed' }
interface Props { config: LetterJumpConfig; onComplete?: (result: LetterJumpResult) => void }
interface Step { round: number; options: string[]; target: string; selected: number }
const shuffle = <T,>(source: T[]) => { const a=[...source]; for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];} return a; };

export default function LetterJumpGame({ config, onComplete }: Props) {
  const items=useMemo(()=>[...new Set(config.items.map(v=>v.trim()).filter(Boolean))],[config.items]);
  const total=Math.max(1,Math.min(config.rounds||8,30));
  const targets=useMemo(()=>{const out:string[]=[];while(out.length<total)out.push(...shuffle(items));return out.slice(0,total);},[items,total]);
  const variants=(answer:string)=>shuffle([answer,...shuffle(items.filter(v=>v!==answer)).slice(0,2)]);
  const [started,setStarted]=useState(false),[finished,setFinished]=useState(false),[locked,setLocked]=useState(false),[jumping,setJumping]=useState(false);
  const [round,setRound]=useState(0),[score,setScore]=useState(0),[mistakes,setMistakes]=useState(0),[wrong,setWrong]=useState<number|null>(null);
  const [options,setOptions]=useState<string[]>([]),[steps,setSteps]=useState<Step[]>([]); const sent=useRef(false);
  const target=targets[round]||items[0]||'';
  const tone=(ok:boolean)=>{try{const C=window.AudioContext||(window as any).webkitAudioContext,a=new C(),o=a.createOscillator(),g=a.createGain();o.type='square';o.frequency.setValueAtTime(ok?520:150,a.currentTime);o.frequency.exponentialRampToValueAtTime(ok?760:90,a.currentTime+.14);g.gain.setValueAtTime(.06,a.currentTime);g.gain.exponentialRampToValueAtTime(.001,a.currentTime+.16);o.connect(g);g.connect(a.destination);o.start();o.stop(a.currentTime+.17);setTimeout(()=>a.close(),250);}catch{}};
  const start=()=>{setStarted(true);setFinished(false);setLocked(false);setRound(0);setScore(0);setMistakes(0);setWrong(null);setSteps([]);setOptions(variants(targets[0]||items[0]));sent.current=false;};
  const choose=(option:string,index:number)=>{if(locked||finished)return;if(option!==target){tone(false);setMistakes(v=>v+1);setWrong(index);setTimeout(()=>setWrong(null),380);return;}setLocked(true);setJumping(true);tone(true);const nextScore=score+10,nextSteps=[...steps,{round,options,target,selected:index}];setScore(nextScore);setSteps(nextSteps);setTimeout(()=>{setJumping(false);if(round+1>=total){setFinished(true);if(!sent.current){sent.current=true;onComplete?.({score:nextScore,total:total*10,mistakes,livesLeft:Math.max(0,(config.lives||3)-mistakes),status:'completed'});}}else{const next=round+1;setRound(next);setOptions(variants(targets[next]));setLocked(false);setWrong(null);}},600);};
  if(items.length<3)return <div className="grid h-full place-items-center bg-sky-100 p-6 text-center font-bold">Добавьте минимум 3 разные буквы или слова.</div>;
  const MAX_VISIBLE_LEVELS=5;
  const LEVEL_GAP=50;
  const visible=steps.slice(-(MAX_VISIBLE_LEVELS-1)), x=[17,50,83];
  const lastSelected=steps.length?steps[steps.length-1].selected:1;
  const playerLeft=steps.length?`calc(${x[lastSelected]}% + ${lastSelected===2?-34:34}px)`:'50%';
  return <div className="mc-game relative h-full min-h-[420px] w-full overflow-hidden font-sans text-white">
    <style>{`.mc-game{image-rendering:pixelated;background:linear-gradient(#65bdf2 0 68%,#bfe9ff 68% 100%)}.mc-cloud{width:30px;height:15px;background:#fff;box-shadow:30px 0 #fff,60px 0 #fff,15px -15px #fff,45px -15px #fff}.mc-box{background:rgba(20,20,20,.88);border:4px solid #5e5e5e;box-shadow:inset 0 0 0 3px #272727,4px 4px 0 rgba(0,0,0,.25);text-transform:uppercase}.mc-platform{background:#7a512d;border:4px solid #3e2b1d;box-shadow:inset 0 11px 0 #65b944,inset 0 16px 0 #3d8730,5px 6px 0 rgba(0,0,0,.22);text-shadow:3px 3px 0 #111;transition:bottom .45s ease,filter .18s}.mc-next{animation:mcPlatformIn .42s ease-out}.mc-platform:hover{filter:brightness(1.12)}@keyframes mcPlatformIn{from{opacity:0;translate:0 -24px}to{opacity:1;translate:0 0}}@keyframes mcShake{25%{translate:-9px}50%{translate:9px}75%{translate:-5px}}@keyframes mcFlash{50%{filter:brightness(1.8);box-shadow:0 0 0 8px rgba(112,255,80,.35),5px 6px 0 rgba(0,0,0,.22)}}@keyframes mcJump{45%{transform:translate(-50%,-160%)}}.mc-wrong{animation:mcShake .35s}.mc-correct{animation:mcFlash .45s}.mc-jump{animation:mcJump .55s ease}.mc-card{background:#c6c6c6;border:6px solid #111;box-shadow:inset 0 0 0 5px #777,8px 8px 0 rgba(0,0,0,.35)}`}</style>
    <div className="absolute right-[7%] top-[7%] h-14 w-14 bg-yellow-300 shadow-[0_0_0_7px_rgba(255,229,92,.2)] sm:h-16 sm:w-16"/><div className="mc-cloud absolute left-[8%] top-[18%] opacity-90"/><div className="mc-cloud absolute right-[17%] top-[30%] scale-75 opacity-80"/>
    <div className="absolute inset-x-2 top-2 z-50 flex items-start justify-center gap-1.5 sm:gap-3"><div className="mc-box min-w-[88px] px-2 py-1 text-center text-[10px] font-black sm:min-w-[120px] sm:text-xs">Раунд<strong className="block text-lg text-yellow-300 sm:text-2xl">{round+1} / {total}</strong></div><div className="mc-box min-w-[112px] max-w-[45%] px-2 py-1 text-center text-[10px] font-black sm:min-w-[150px] sm:text-xs">Найди<strong className="block truncate text-xl text-yellow-300 sm:text-3xl">{target}</strong></div><div className="mc-box min-w-[76px] px-2 py-1 text-center text-[10px] font-black sm:min-w-[105px] sm:text-xs">Очки<strong className="block text-lg text-yellow-300 sm:text-2xl">{score}</strong></div></div>
    <div className="absolute inset-0 overflow-hidden"><div className="absolute inset-x-0 bottom-0 h-[70px] border-t-[15px] border-[#5daf3e] bg-[#79512d]" style={{backgroundImage:'linear-gradient(90deg,rgba(0,0,0,.08) 1px,transparent 1px),linear-gradient(rgba(0,0,0,.08) 1px,transparent 1px)',backgroundSize:'30px 30px'}}/>
      {visible.map((step,v)=>step.options.map((option,i)=><div key={`${step.round}-${i}`} className={`mc-platform absolute flex h-9 w-[27%] max-w-[142px] items-center justify-center overflow-hidden px-1 text-lg font-black sm:h-10 sm:text-2xl ${i===step.selected?'mc-correct':'opacity-75'}`} style={{left:`${x[i]}%`,bottom:75+v*LEVEL_GAP,transform:'translateX(-50%)'}}>{option}</div>))}
      {!finished&&options.map((option,i)=><button key={`${round}-${i}`} onClick={()=>choose(option,i)} className={`mc-platform mc-next absolute z-20 flex h-10 w-[27%] max-w-[142px] items-center justify-center overflow-hidden px-1 text-xl font-black sm:h-11 sm:text-2xl ${wrong===i?'mc-wrong':''} ${locked&&option===target?'mc-correct':''}`} style={{left:`${x[i]}%`,bottom:75+Math.min(visible.length,MAX_VISIBLE_LEVELS-1)*LEVEL_GAP,transform:'translateX(-50%)'}}>{option}</button>)}
      <div className={`absolute z-30 h-16 w-11 -translate-x-1/2 transition-[left,bottom] duration-500 ${jumping?'mc-jump':''}`} style={{left:playerLeft,bottom:steps.length?75+(visible.length-1)*LEVEL_GAP+44:70}}><div className="absolute left-[7px] top-0 h-7 w-7 border-4 border-[#3b2a20] bg-[#c98b5c] shadow-[inset_7px_0_#8b5b3d]"><i className="absolute right-1 top-1 h-1 w-1 bg-white shadow-[3px_0_#222]"/></div><div className="absolute left-1 top-7 h-6 w-[34px] border-4 border-[#173f43] bg-[#36a6a1]"/><div className="absolute bottom-0 left-1 h-4 w-4 border-[3px] border-[#1d284e] bg-[#394e97]"/><div className="absolute bottom-0 right-1 h-4 w-4 border-[3px] border-[#1d284e] bg-[#394e97]"/></div>
    </div>
    <div className="absolute bottom-2 left-1/2 z-40 w-[min(94%,560px)] -translate-x-1/2 border-4 border-[#777] bg-black/90 px-3 py-2 text-center text-xs font-black sm:text-sm">{locked?'Верно! Поднимаемся выше.':config.instruction||`Прыгни на платформу ${target}`}</div>
    {!started&&<div className="absolute inset-0 z-[100] flex items-center justify-center bg-black/50 p-4"><div className="mc-card w-[min(520px,94%)] p-5 text-center text-slate-900"><h1 className="mb-2 text-2xl font-black uppercase sm:text-4xl">{config.title||'Alphabet Craft'}</h1><p className="mb-4 text-sm font-bold sm:text-base">Пройди {total} раундов. Каждый раз выбирай правильную платформу.</p><button onClick={start} className="border-4 border-black bg-[#6cab3d] px-7 py-2 font-black text-white shadow-[inset_0_0_0_3px_#93d260,4px_4px_0_rgba(0,0,0,.25)]">Начать</button></div></div>}
    {finished&&<div className="absolute inset-0 z-[100] flex items-center justify-center bg-black/50 p-4"><div className="mc-card w-[min(480px,94%)] p-6 text-center text-slate-900"><h1 className="text-3xl font-black uppercase sm:text-4xl">Готово!</h1><p className="mt-3 font-bold">Ты прошёл {total} раундов и набрал {score} очков.</p><p className="mt-1 font-bold text-slate-600">Ошибок: {mistakes}</p></div></div>}
  </div>;
}
